### ISSUE TITLE
 Minor fixes ... a bit too minor

### ISSUE THREAD

**Issue by i-e-b** [feramhq/feram#14]
https://github.com/i-e-b/WindowsJedi/pull/1

Nice bot, but a single missing letter in a comment seems _not worth it_... especially for a repo that no-one uses (except myself)

(plus, I'm sure there are loads of typos in there is missed :-)

**Comment by bfred-it** [comment]
Not worth what? It takes a click to merge the PR. If you're referring to the time it takes to manually build/publish the update, then you can still merge now and wait until the next time you decide to do that :smile:

**Comment by adius** [comment]
Thanks @bfred-it for the support! That's also exactly what I think.
There is no bug too minor for a single click on "merge pull-request" =D

> (plus, I'm sure there are loads of typos in there is missed :-)

I guess so 😄 …but hopefully the next version of Feram won't miss them 😉
It's all about incremental improvements!

As you seem to be the only one having this concerns,
I'm going to close the issue for the time being…

**Comment by i-e-b** [comment]
Sorry @adius for dragging this thread back from the dead, but I was having a discussion with a friend and it reminded me of this.

I didn't take the time to explain why there was any effort beyond "a single click". Sometimes, the Github version of a project is a mirror, in which case it's not a single click (this is the case for the repo mentioned above). A more tricky one is the case of copyright ownership. Lots of countries favour strict protection of the 'creators' of a 'work', rather than any sense of contribution to an overall project (open projects don't seem to exist in the law and lobbying sphere). When a contribution is accepted to a project in many legal systems (including the UK as USA to the best of my knowledge), if no statement of release or issue of licensing terms is given, the contributor has some level of legal claim for the parts they contributed.

It might be helpful for the 'bot to give a release (like "these changes are granted to the rights holder of of the main work" or something like that... AANAL).

Thanks, and I hope that makes me seem a *little* less of a grumpy dev.

**Comment by adius** [comment]
No problem at all. Especially if it's such an interesting comment =)
Thanks for bringing up the potential copyright problems.
This is indeed something we haven't really thought about yet.
I'll create an internal issue and we'll have a closer look!

About unwanted pull-requests:
We think the main problem is that GitHub has no mechanism to disable pull requests for repos.
It's possible to disable issues and the wiki, but not pull requests…
We already contacted GitHub about this, but they don't seem to care… =(
We also look into other ways to recognize a repo where pull requests are unwanted.
…but it's actually not clear on which metrics this decision should be based.
