### ISSUE TITLE
I will likely get annoyed very quickly

### ISSUE THREAD

**Issue by pombredanne** [feramhq/feram#17]
PR from bots sound like a good idea.... within reason. Trivial spelling corrections and related variable renaming are IMHO just noise.... And furthermore, if the bot and "rules" that underpin this are not part of an open source project this is even more annoying.
Just my 2 cents. Sorry to be a party pooper

**Comment by stefanberndtsson** [comment]
Agreed. Single letter PR's that contains loads of irrelevant text, AND causes alerts in the mail, is way more noisy than the single letter was in the first place. This is abuse-report-worthy if it continues without going opt-in. No, making the repos private is not an opt-in feature, it's an opt-out feature, and a bad one at that.

**Comment by pombredanne** [comment]
@adius I guess you are the perpetrator.... do you care to chime in?

**Comment by pombredanne** [comment]
here is a random example of a f**ck**ly stupid thing: https://github.com/AaronLayton/rNet/pull/1/files#diff-478dbf8e72cf8687706aa1bbd83fc405L85
@adius please stop that sh**t

**Comment by adius** [comment]
Thanks for your feedback!

This topic has already come up: https://github.com/feramhq/feram/issues/16
So please make sure to check out the corresponding answer.

I'm sorry about the unfavorable typo-fix in the rNet repo
and created an issue for it: https://github.com/feramhq/feram/issues/22

Generally we strive for a minimal false positive rate and
are currently way below 1%. We're working hard to get
even better, but in this order of magnitude I'm generally
not concerned. I guess it's probably even better than most humans =D.

**Comment by pombredanne** [comment]
@adius if you continue running this stupid bot and unless I have asked for it as a service on my repos, I will report you to Github as spam and to get you banned.

**Comment by adius** [comment]
@pombredanne I just checked out your pull requests and at this point I can't take you serious any more.
You yourself created [50+ pull requests which only correct typing errors](https://github.com/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Apombredanne+typo+) and spelling mistakes.
But at the same time you claim 
> Trivial spelling corrections and related variable renaming are IMHO just noise

This is just utterly ridiculous. I guess you are just a troll … so please annoy people on another website.
