### ISSUE TITLE
Exclude data files -> .csv

### ISSUE THREAD

**Issue by stephantul** [feramhq/feram#19]
Your bot fixed a "typo" in a .csv filled with spelling variants.
I get that fixing typos is handy when it concerns source code, comments, or documentation, but why would you change values in a .csv file that is meant to be read as data?

Is it possible you could provide an opt-in, or at the very least an opt-out, for this service?

**Comment by adius** [comment]
Thanks for your feedback!
Can you please add a link to the pull request, I wasn't able to find it.

Add the moment we blacklist files which should not be checked.
I guess we need to extend it with `.*(vocabulary|typo|spelling-mistake|…).*`

Blacklisting all csv files sounds a little too drastic to me.
Csv files often contain textual data, so it makes sense to check them as well.
We will look further into the issue and if we happen to discover that csv
files lead to too many false positives, we will exclude them completely.

We are working, on the opt-out/in: https://github.com/feramhq/feram/issues/21
Until we've solved this issue there will be no more pull requests from Feram on his own.

**Comment by adius** [comment]
Also created an issue for blacklisting vocabulary files: https://github.com/feramhq/feram/issues/26

**Comment by stephantul** [comment]
Thanks for your response! For the record: I don't think this is a bad idea at all, it just needs some fine-tuning I think. It would be great, for example, to have it conform python code to `pep8` or something.

The pull request is [here](https://github.com/stephantul/tacosdetection/pull/1). Feram corrected `sergent`, which is a Dutch word for someone from an ethnic group to `sergeant`. It is an understandable False Positive, but it could have been avoided by not touching data .csv files or doing language detection first.

**Comment by adius** [comment]
We strive to achieve a 0% rate for false positives, so I added "sergent -> sergeant" to a blacklist of typo corrections
which can't achieve this false positive rate. => Won't happen again =)

**Comment by adius** [comment]
@stephantul pep8 is now integrated 😁 . Check it out at https://feram.io

Btw: Feram is not running fully automatically anymore. Patches are always checked before creating a merge request, so I'm closing this for the time being.
