### ISSUE TITLE
Fixing typos that are there on purpose

### ISSUE THREAD

**Issue by wolfascu** [feramhq/feram#20]
Hi!

Just got a pull request from Feram: https://github.com/wolfascu/codegolf/pull/1

The code there was meant to solve [this challenge](http://codegolf.stackexchange.com/questions/45168/grow-words-from-fertile-vocabularies) and the bot found an incorrectly spelled word in a dictionary file that was provided as part of the challenge itself.

So, while Feram may technically be correct, I will reject the pull request.

Anyway, cool idea! :smile:

**Comment by adius** [comment]
Created an issue for this: https://github.com/feramhq/feram/issues/26
