### ISSUE TITLE
Let users opt-out of future pull requests

### ISSUE THREAD

**Issue by adius** [feramhq/feram#21]
Idea:
Users can add a `feram.yaml` or `.feram.yaml` file
with a `disallow: *` field to specify which files should not be checked for bugs.
`*` can be any valid [minimatch](https://github.com/isaacs/minimatch) supported glob expression.

**Comment by adius** [comment]
Or even better:
Each pull request contains two links:
- Don't send any more pull requests to this user
- Don't send any more pull requests to this repository

**Comment by ebekebe** [comment]
Having feram in the name of the file would require additional files for other bots with a different name. I suggest to have something like the [robots](http://www.robotstxt.org/) file on the web. The simplest thing here would be a total opt-out for all robots.

**Comment by stefanberndtsson** [comment]
Having the "Don't bother me"-links in the PR is the only reasonable and non-intrusive way to implement opt-out. Making every repository handle whether or not it should be opted-out is intrusive and not practical in any way. Imagine a user with a few hundred repos. Adding a file to each and everyone of these is a poor solution.

**Comment by adius** [comment]
Yeah, I also thought about the robots.txt solution.
But the problem is that it can't be distinguished if the repo should
be ignored or the website contained in the repo after its published.
We would have to come up with something a little different.
Maybe `robots.yaml`. If we want to create a platform/technology independent
solution, however, we would nee partners and have a formal specification.
(Something like semver.org)

**Comment by pombredanne** [comment]
One more (and last) time: having a service like this as an opt-in GH service could be something I could use. I should never have to opt-out because a bot should never start bugging me unless I asked for it.

**Comment by ad-si** [comment]
No more bot merge requests. Turns out it's basically impossible without annoying someone (even if it's just a small fraction…)
