### ISSUE TITLE
Typos in 3rd party libraries..

### ISSUE THREAD

**Issue by greenish** [feramhq/feram#29]
This is a tricky one, but the only typos Feram found in my repo were in 3rd party libraries' comments that were bundled in my dist/ folder.. 

Still, nice project :)

**Comment by adius** [comment]
Thanks for the heads up! We're relying on https://github.com/github/linguist/blob/master/lib/linguist/vendor.yml for filtering out vendor files.
I guess `dist` would be a good addition! I created a pull request at: https://github.com/github/linguist/pull/3182 😊

**Comment by adius** [comment]
The pull request was merged! =)
